[package]
name = "rock"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
axum = "0.8.4"
axum-extra = { version = "0.10.1", features = ["typed-header"] }
clap = { version = "4.5.42", features = ["derive"] }
env_logger= { workspace = true }
futures = "0.3.31"
k8s-openapi = { workspace = true, features = ["latest"] }
kube = { workspace = true, features = ["runtime", "derive"] }
log = { workspace = true }
rock-types = { path = "rock-types" }
schemars ={ workspace = true }
secrecy = "0.10.3"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
thiserror = "2.0.12"
tokio = { workspace = true, features = ["macros", "net", "rt-multi-thread", "sync"] }
tower-http = { version = "0.6.8", features = ["cors"] }
uuid = { workspace = true, features = ["v4", "serde"] }

[workspace]
members = ["rock-types"]

[workspace.dependencies]
anyhow = "1.0.98"
env_logger = "0.11.8"
log = "0.4.27"
k8s-openapi = { version = "0.25.0", features = ["latest"] }
kube = { version = "1.1.0", features = ["runtime", "derive"] }
schemars = "0.8.22"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
# TODO : replace by saphir once saphir-serde is available
serde_yaml = "0.9.34"
tokio = { version = "1.47.1", features = ["macros", "net", "rt-multi-thread", "sync"] }
uuid = { version = "1.17.0", features = ["v4", "serde"] }
